# Generated by Django 5.0.14 on 2025-12-04 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt Text')),
                ('caption', models.TextField(blank=True, verbose_name='Açıklama')),
                ('file', models.FileField(upload_to='media/%Y/%m/', verbose_name='Dosya')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/')),
                ('file_type', models.CharField(choices=[('image', 'Görsel'), ('video', 'Video'), ('audio', 'Ses'), ('document', 'Doküman')], max_length=20, verbose_name='Dosya Tipi')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Dosya Boyutu (bytes)')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Süre (saniye)')),
                ('copyright_holder', models.CharField(blank=True, max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medya',
                'verbose_name_plural': 'Medya Dosyaları',
                'ordering': ['-created_at'],
            },
        ),
    ]
