# Generated by Django 5.0.14 on 2025-12-04 18:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user_type', models.CharField(choices=[('admin', 'Yönetici'), ('editor', 'Editör'), ('author', 'Yazar'), ('subscriber', 'Abone'), ('reader', 'Okuyucu')], default='reader', max_length=20, verbose_name='Kullanıcı Tipi')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Biyografi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Email Doğrulandı')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='Görünen Ad')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('title', models.CharField(blank=True, help_text='Örn: Kıdemli Muhabir', max_length=100, verbose_name='Ünvan')),
                ('specialty', models.CharField(blank=True, help_text='Örn: Spor Muhabirliği', max_length=100, verbose_name='Uzmanlık Alanı')),
                ('bio_long', models.TextField(blank=True, verbose_name='Detaylı Biyografi')),
                ('social_twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('social_linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('social_instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('social_facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('total_articles', models.PositiveIntegerField(default=0, verbose_name='Toplam Haber Sayısı')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='Toplam Görüntülenme')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Ortalama Puan')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan Yazar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Yazar Profili',
                'verbose_name_plural': 'Yazar Profilleri',
                'ordering': ['-total_articles'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email Bildirimleri')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push Bildirimleri')),
                ('newsletter_subscribed', models.BooleanField(default=False, verbose_name='Newsletter Aboneliği')),
                ('language', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English')], default='tr', max_length=2, verbose_name='Dil')),
                ('theme', models.CharField(choices=[('light', 'Açık'), ('dark', 'Koyu'), ('auto', 'Otomatik')], default='light', max_length=10, verbose_name='Tema')),
                ('font_size', models.CharField(default='medium', max_length=10, verbose_name='Font Boyutu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Tercihi',
                'verbose_name_plural': 'Kullanıcı Tercihleri',
            },
        ),
        migrations.CreateModel(
            name='UserPreferredCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_categories', to='accounts.userpreference')),
            ],
            options={
                'verbose_name': 'Tercih Edilen Kategori',
                'verbose_name_plural': 'Tercih Edilen Kategoriler',
                'ordering': ['order'],
                'unique_together': {('preference', 'category')},
            },
        ),
    ]
