# Generated by Django 5.0.14 on 2026-01-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list, verbose_name='Yedek Kodlar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, verbose_name='TOTP Secret Key'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='İki Faktörlü Kimlik Doğrulama Aktif'),
        ),
    ]
