# Generated by Django 5.0.14 on 2025-12-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Etiket Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Kullanım Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Etiket',
                'verbose_name_plural': 'Etiketler',
                'ordering': ['-usage_count', 'name'],
                'indexes': [models.Index(fields=['slug'], name='tags_tag_slug_dcb0c2_idx'), models.Index(fields=['-usage_count'], name='tags_tag_usage_c_be8d76_idx')],
            },
        ),
    ]
