# Generated by Django 5.0.14 on 2025-12-04 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Beğenilme Tarihi')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='articles.article', verbose_name='Haber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Beğeni',
                'verbose_name_plural': 'Beğeniler',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article', '-created_at'], name='interaction_article_9d4426_idx'), models.Index(fields=['user', '-created_at'], name='interaction_user_id_8c86b9_idx')],
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('email', 'E-posta'), ('copy', 'Link Kopyala')], max_length=20, verbose_name='Platform')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Paylaşım Tarihi')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='articles.article', verbose_name='Haber')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Paylaşım',
                'verbose_name_plural': 'Paylaşımlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article', '-created_at'], name='interaction_article_a62613_idx'), models.Index(fields=['platform', '-created_at'], name='interaction_platfor_94782a_idx')],
            },
        ),
    ]
