# Generated by Django 5.0.14 on 2025-12-04 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Klasör Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Renk Kodu')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='İkon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_folders', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Bookmark Klasörü',
                'verbose_name_plural': 'Bookmark Klasörleri',
                'ordering': ['order', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Liste Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_public', models.BooleanField(default=False, verbose_name='Herkese Açık')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_lists', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Okuma Listesi',
                'verbose_name_plural': 'Okuma Listeleri',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Not')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Etiketler')),
                ('reminder_date', models.DateTimeField(blank=True, null=True, verbose_name='Hatırlatma Tarihi')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Hatırlatma Gönderildi')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favori')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='articles.article', verbose_name='Haber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='bookmarks.bookmarkfolder', verbose_name='Klasör')),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='bookmarks_b_user_id_6ce37d_idx'), models.Index(fields=['user', 'is_favorite'], name='bookmarks_b_user_id_a739a6_idx'), models.Index(fields=['user', 'is_read'], name='bookmarks_b_user_id_e6c320_idx')],
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_percentage', models.PositiveIntegerField(default=0, verbose_name='Okuma Yüzdesi')),
                ('scroll_depth', models.PositiveIntegerField(default=0, verbose_name='Scroll Derinliği')),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='Geçirilen Süre (sn)')),
                ('device_type', models.CharField(blank=True, max_length=20, verbose_name='Cihaz Tipi')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Okuma Zamanı')),
                ('last_position', models.TextField(blank=True, verbose_name='Son Konum')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='articles.article', verbose_name='Haber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Okuma Geçmişi',
                'verbose_name_plural': 'Okuma Geçmişleri',
                'ordering': ['-read_at'],
                'indexes': [models.Index(fields=['user', '-read_at'], name='bookmarks_r_user_id_90fdf1_idx'), models.Index(fields=['user', 'article'], name='bookmarks_r_user_id_b569b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReadingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('note', models.TextField(blank=True, verbose_name='Not')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Haber')),
                ('reading_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookmarks.readinglist', verbose_name='Okuma Listesi')),
            ],
            options={
                'verbose_name': 'Okuma Listesi Öğesi',
                'verbose_name_plural': 'Okuma Listesi Öğeleri',
                'ordering': ['order', '-added_at'],
                'unique_together': {('reading_list', 'article')},
            },
        ),
    ]
