# Generated by Django 5.0.14 on 2025-12-04 18:43

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
        ('media_app', '0001_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Alt Başlık')),
                ('summary', models.TextField(max_length=500, verbose_name='Özet')),
                ('content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('has_video', models.BooleanField(default=False, verbose_name='Video İçeriyor')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL (YouTube, Vimeo, vb.)')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video Dosyası')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', verbose_name='Video Küçük Resmi')),
                ('video_duration', models.PositiveIntegerField(default=0, verbose_name='Video Süresi (saniye)')),
                ('video_embed_code', models.TextField(blank=True, verbose_name='Video Embed Kodu')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('pending', 'Onay Bekliyor'), ('published', 'Yayınlandı'), ('archived', 'Arşiv')], default='draft', max_length=20, verbose_name='Durum')),
                ('visibility', models.CharField(choices=[('public', 'Herkese Açık'), ('premium', 'Premium Üyeler'), ('subscriber_only', 'Sadece Aboneler')], default='public', max_length=20, verbose_name='Görünürlük')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Manşet')),
                ('is_breaking', models.BooleanField(default=False, verbose_name='Son Dakika')),
                ('is_trending', models.BooleanField(default=False, verbose_name='Gündemde')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme')),
                ('read_time', models.PositiveIntegerField(default=0, verbose_name='Okuma Süresi (dk)')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Yayın Tarihi')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Geçerlilik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og_images/', verbose_name='OG Image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='accounts.authorprofile', verbose_name='Yazar')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='categories.category', verbose_name='Kategori')),
                ('co_authors', models.ManyToManyField(blank=True, related_name='co_authored_articles', to='accounts.authorprofile', verbose_name='Ortak Yazarlar')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_articles', to='media_app.media', verbose_name='Öne Çıkan Görsel')),
                ('gallery', models.ManyToManyField(blank=True, related_name='article_galleries', to='media_app.media', verbose_name='Galeri')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='tags.tag', verbose_name='Etiketler')),
            ],
            options={
                'verbose_name': 'Haber',
                'verbose_name_plural': 'Haberler',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('revision_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='articles.article')),
                ('revised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelatedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('similar', 'Benzer'), ('continuation', 'Devamı'), ('background', 'Arka Plan')], default='similar', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='articles.article')),
                ('related_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='articles.article')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_at'], name='articles_ar_publish_c1a2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status'], name='articles_ar_status_edb746_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_breaking'], name='articles_ar_is_brea_49679e_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_featured'], name='articles_ar_is_feat_d43b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_trending'], name='articles_ar_is_tren_9412e4_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-views_count'], name='articles_ar_views_c_a0dd47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='relatedarticle',
            unique_together={('article', 'related_article')},
        ),
    ]
