# Generated by Django 5.0.14 on 2025-12-04 18:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Reklam Adı')),
                ('ad_type', models.CharField(choices=[('image', 'Görsel Reklam'), ('html', 'HTML Reklam'), ('video', 'Video Reklam'), ('script', 'Script (AdSense vb.)'), ('native', 'Native Reklam')], max_length=20, verbose_name='Reklam Tipi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisements/', verbose_name='Görsel')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('html_content', models.TextField(blank=True, verbose_name='HTML İçerik')),
                ('script_code', models.TextField(blank=True, verbose_name='Script Kodu')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='advertisements/thumbnails/', verbose_name='Küçük Resim')),
                ('target_url', models.URLField(verbose_name='Hedef URL')),
                ('open_in_new_tab', models.BooleanField(default=True, verbose_name='Yeni Sekmede Aç')),
                ('priority', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Öncelik (0-100)')),
                ('weight', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ağırlık')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='Gösterim')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Tıklama')),
                ('conversions', models.PositiveIntegerField(default=0, verbose_name='Dönüşüm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reklam',
                'verbose_name_plural': 'Reklamlar',
                'ordering': ['-priority', '-weight', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Bölge Adı')),
                ('zone_type', models.CharField(choices=[('banner_top', 'Üst Banner'), ('banner_bottom', 'Alt Banner'), ('sidebar_top', 'Sidebar Üst'), ('sidebar_middle', 'Sidebar Orta'), ('sidebar_bottom', 'Sidebar Alt'), ('in_article_top', 'Makale İçi Üst'), ('in_article_middle', 'Makale İçi Orta'), ('in_article_bottom', 'Makale İçi Alt'), ('floating', 'Floating/Sticky'), ('popup', 'Pop-up'), ('interstitial', 'Tam Sayfa'), ('native', 'Native/İçerik Arası')], max_length=50, verbose_name='Bölge Tipi')),
                ('width', models.PositiveIntegerField(verbose_name='Genişlik (px)')),
                ('height', models.PositiveIntegerField(verbose_name='Yükseklik (px)')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reklam Bölgesi',
                'verbose_name_plural': 'Reklam Bölgeleri',
                'ordering': ['zone_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Firma Adı')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('website', models.URLField(blank=True, verbose_name='Web Sitesi')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='İlgili Kişi')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='Vergi Numarası')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reklamveren',
                'verbose_name_plural': 'Reklamverenler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdBlockDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('page_url', models.URLField(verbose_name='Sayfa URL')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Tespit Zamanı')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'AdBlock Tespiti',
                'verbose_name_plural': 'AdBlock Tespitleri',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Ülke')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Şehir')),
                ('device_type', models.CharField(blank=True, max_length=20, verbose_name='Cihaz Tipi')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Tarayıcı')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='İşletim Sistemi')),
                ('page_url', models.URLField(verbose_name='Sayfa URL')),
                ('referrer', models.URLField(blank=True, verbose_name='Referrer')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Görüntülenme Zamanı')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impression_records', to='advertisements.advertisement', verbose_name='Reklam')),
            ],
            options={
                'verbose_name': 'Reklam Gösterimi',
                'verbose_name_plural': 'Reklam Gösterimleri',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Ülke')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Şehir')),
                ('device_type', models.CharField(blank=True, max_length=20, verbose_name='Cihaz Tipi')),
                ('page_url', models.URLField(verbose_name='Sayfa URL')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='Tıklanma Zamanı')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('impression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='advertisements.adimpression', verbose_name='Gösterim')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_records', to='advertisements.advertisement', verbose_name='Reklam')),
            ],
            options={
                'verbose_name': 'Reklam Tıklaması',
                'verbose_name_plural': 'Reklam Tıklamaları',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='AdConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_type', models.CharField(choices=[('registration', 'Kayıt'), ('subscription', 'Abonelik'), ('purchase', 'Satın Alma'), ('lead', 'Lead/İlgi'), ('download', 'İndirme'), ('custom', 'Özel')], max_length=20, verbose_name='Dönüşüm Tipi')),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Dönüşüm Değeri (₺)')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('converted_at', models.DateTimeField(auto_now_add=True, verbose_name='Dönüşüm Zamanı')),
                ('click', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='advertisements.adclick', verbose_name='Tıklama')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_records', to='advertisements.advertisement', verbose_name='Reklam')),
            ],
            options={
                'verbose_name': 'Reklam Dönüşümü',
                'verbose_name_plural': 'Reklam Dönüşümleri',
                'ordering': ['-converted_at'],
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertisements', to='advertisements.advertisementzone', verbose_name='Reklam Bölgesi'),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kampanya Adı')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('scheduled', 'Planlandı'), ('active', 'Aktif'), ('paused', 'Duraklatıldı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='draft', max_length=20, verbose_name='Durum')),
                ('pricing_model', models.CharField(choices=[('cpm', 'CPM (Bin Gösterim)'), ('cpc', 'CPC (Tıklama Başına)'), ('cpa', 'CPA (Eylem Başına)'), ('flat', 'Sabit Ücret')], max_length=20, verbose_name='Fiyatlandırma Modeli')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bütçe (₺)')),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Harcanan (₺)')),
                ('cpm_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='CPM Fiyatı (₺)')),
                ('cpc_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='CPC Fiyatı (₺)')),
                ('cpa_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='CPA Fiyatı (₺)')),
                ('max_impressions', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maksimum Gösterim')),
                ('max_clicks', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maksimum Tıklama')),
                ('daily_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Günlük Bütçe (₺)')),
                ('start_date', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateTimeField(verbose_name='Bitiş Tarihi')),
                ('target_countries', models.JSONField(blank=True, default=list, verbose_name='Hedef Ülkeler')),
                ('target_cities', models.JSONField(blank=True, default=list, verbose_name='Hedef Şehirler')),
                ('target_devices', models.JSONField(blank=True, default=list, verbose_name='Hedef Cihazlar')),
                ('total_impressions', models.PositiveIntegerField(default=0, verbose_name='Toplam Gösterim')),
                ('total_clicks', models.PositiveIntegerField(default=0, verbose_name='Toplam Tıklama')),
                ('total_conversions', models.PositiveIntegerField(default=0, verbose_name='Toplam Dönüşüm')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='advertisements.advertiser', verbose_name='Reklamveren')),
                ('target_categories', models.ManyToManyField(blank=True, to='categories.category', verbose_name='Hedef Kategoriler')),
            ],
            options={
                'verbose_name': 'Kampanya',
                'verbose_name_plural': 'Kampanyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='advertisements.campaign', verbose_name='Kampanya'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['advertisement', '-viewed_at'], name='advertiseme_adverti_fbb68f_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['ip_address', 'advertisement', '-viewed_at'], name='advertiseme_ip_addr_094705_idx'),
        ),
        migrations.AddIndex(
            model_name='adconversion',
            index=models.Index(fields=['advertisement', '-converted_at'], name='advertiseme_adverti_b9a29a_idx'),
        ),
        migrations.AddIndex(
            model_name='adclick',
            index=models.Index(fields=['advertisement', '-clicked_at'], name='advertiseme_adverti_06f2fb_idx'),
        ),
        migrations.AddIndex(
            model_name='adclick',
            index=models.Index(fields=['ip_address', 'advertisement', '-clicked_at'], name='advertiseme_ip_addr_31a1d5_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='advertiseme_status_b9e6e8_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['advertiser', '-created_at'], name='advertiseme_adverti_681615_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['zone', '-priority', '-weight'], name='advertiseme_zone_id_638f65_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['campaign', 'is_active'], name='advertiseme_campaig_0c6e5d_idx'),
        ),
    ]
