# Generated by Django 5.0.14 on 2025-12-04 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('device_type', models.CharField(blank=True, choices=[('mobile', 'Mobil'), ('tablet', 'Tablet'), ('desktop', 'Masaüstü')], max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='articles.article')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Haber Görüntülenme',
                'verbose_name_plural': 'Haber Görüntülenmeler',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['article', '-viewed_at'], name='analytics_a_article_ce7603_idx'), models.Index(fields=['user', '-viewed_at'], name='analytics_a_user_id_1a9825_idx')],
            },
        ),
        migrations.CreateModel(
            name='PopularArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Günlük'), ('weekly', 'Haftalık'), ('monthly', 'Aylık'), ('all_time', 'Tüm Zamanlar')], max_length=20)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('score', models.FloatField(default=0.0, verbose_name='Popülerlik Skoru')),
                ('date', models.DateField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popularity_records', to='articles.article')),
            ],
            options={
                'verbose_name': 'Popüler Haber',
                'verbose_name_plural': 'Popüler Haberler',
                'ordering': ['-score', '-views_count'],
                'indexes': [models.Index(fields=['period', '-score'], name='analytics_p_period_fd4c73_idx')],
                'unique_together': {('article', 'period', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SocialShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_shares', to='articles.article')),
            ],
            options={
                'verbose_name': 'Sosyal Medya Paylaşımı',
                'verbose_name_plural': 'Sosyal Medya Paylaşımları',
                'unique_together': {('article', 'platform')},
            },
        ),
    ]
