# Generated by Django 5.0.14 on 2026-01-24 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_comment', models.BooleanField(default=True, verbose_name='Yorum Email')),
                ('email_on_reply', models.BooleanField(default=True, verbose_name='Yanıt Email')),
                ('email_on_like', models.BooleanField(default=False, verbose_name='Beğeni Email')),
                ('email_on_follow', models.BooleanField(default=True, verbose_name='Takip Email')),
                ('email_on_mention', models.BooleanField(default=True, verbose_name='Bahsetme Email')),
                ('push_on_comment', models.BooleanField(default=True, verbose_name='Yorum Push')),
                ('push_on_reply', models.BooleanField(default=True, verbose_name='Yanıt Push')),
                ('push_on_like', models.BooleanField(default=True, verbose_name='Beğeni Push')),
                ('push_on_follow', models.BooleanField(default=True, verbose_name='Takip Push')),
                ('push_on_mention', models.BooleanField(default=True, verbose_name='Bahsetme Push')),
                ('inapp_on_comment', models.BooleanField(default=True, verbose_name='Yorum In-App')),
                ('inapp_on_reply', models.BooleanField(default=True, verbose_name='Yanıt In-App')),
                ('inapp_on_like', models.BooleanField(default=True, verbose_name='Beğeni In-App')),
                ('inapp_on_follow', models.BooleanField(default=True, verbose_name='Takip In-App')),
                ('inapp_on_mention', models.BooleanField(default=True, verbose_name='Bahsetme In-App')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Bildirim Tercihi',
                'verbose_name_plural': 'Bildirim Tercihleri',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('comment', 'Yorum'), ('reply', 'Yanıt'), ('like', 'Beğeni'), ('follow', 'Takip'), ('article', 'Yeni Makale'), ('mention', 'Bahsetme'), ('system', 'Sistem')], max_length=20, verbose_name='Bildirim Tipi')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu mu?')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Okunma Tarihi')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
    ]
